# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\details.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(773, 225)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 180, 771, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.nameTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.nameTextEdit.setGeometry(QtCore.QRect(110, 20, 641, 41))
        self.nameTextEdit.setStyleSheet("font:13px;")
        self.nameTextEdit.setObjectName("nameTextEdit")
        self.nameLabel = QtWidgets.QLabel(Dialog)
        self.nameLabel.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.nameLabel.setStyleSheet("font: 15px")
        self.nameLabel.setObjectName("nameLabel")
        self.pathTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.pathTextEdit.setGeometry(QtCore.QRect(110, 70, 591, 41))
        self.pathTextEdit.setStyleSheet("font:13px;")
        self.pathTextEdit.setObjectName("pathTextEdit")
        self.pathLabel = QtWidgets.QLabel(Dialog)
        self.pathLabel.setGeometry(QtCore.QRect(20, 70, 81, 41))
        self.pathLabel.setStyleSheet("font: 15px")
        self.pathLabel.setObjectName("pathLabel")
        self.parametersTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.parametersTextEdit.setGeometry(QtCore.QRect(110, 120, 641, 41))
        self.parametersTextEdit.setStyleSheet("font:13px;")
        self.parametersTextEdit.setObjectName("parametersTextEdit")
        self.parametersLabel = QtWidgets.QLabel(Dialog)
        self.parametersLabel.setGeometry(QtCore.QRect(20, 120, 81, 41))
        self.parametersLabel.setStyleSheet("font: 15px")
        self.parametersLabel.setObjectName("parametersLabel")
        self.openPathButton = QtWidgets.QPushButton(Dialog)
        self.openPathButton.setGeometry(QtCore.QRect(710, 70, 41, 41))
        self.openPathButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openPathButton.setIcon(icon)
        self.openPathButton.setIconSize(QtCore.QSize(29, 29))
        self.openPathButton.setObjectName("openPathButton")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Game Details"))
        self.nameTextEdit.setPlainText(_translate("Dialog", "Heroes of Might and Magic 7"))
        self.nameLabel.setText(_translate("Dialog", "Name:"))
        self.pathTextEdit.setPlainText(_translate("Dialog", "E:\\Games\\Might and Magic Heroes VII\\Binaries\\Win64\\MMH7Game-Win64-Shipping.exeE\\Games\\Might and Magic Heroes VII\\Binaries\\Win64"))
        self.pathLabel.setText(_translate("Dialog", "Path:"))
        self.parametersTextEdit.setPlainText(_translate("Dialog", "--steam-build -m -parameters"))
        self.parametersLabel.setText(_translate("Dialog", "Parameters:"))
import resources_rc
